[project]
name = "backend-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "granian>=2.5.0",
    "reload>=0.9",
    "pytest>=8.0.0",
    "httpx>=0.27.0",
]
